# Dockerfile for Frontend
FROM node:20

WORKDIR /app

# התקנת תלויות
COPY package*.json ./
RUN npm install

# העתקת שאר הקוד
COPY . .

# בניית האפליקציה
RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--host"]

