version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - lucky_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - lucky_network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.bot
    networks:
      - lucky_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lucky_network
    depends_on:
      - frontend
      - backend

networks:
  lucky_network:
    driver: bridge
